In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
import numpy
import pandas as pd 
import tensorflow as tf 


In [3]:
seed = 0 
numpy.random.seed(seed)
tf.random.set_seed(3)

In [4]:
df = pd.read_csv("/content/drive/MyDrive/housing.csv",delim_whitespace=True,header=None)

In [5]:
dataset = df.values

In [6]:
dataset.shape

(506, 14)

In [7]:
X = dataset[:,0:13].astype(float)
Y = dataset[:,13].astype(float)

In [8]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3, random_state= seed)

In [9]:
X_train.shape

(354, 13)

In [10]:
X_test.shape

(152, 13)

In [11]:
Y_train.shape

(354,)

In [12]:
Y_train

array([14.4, 24.4, 18.1, 22.5, 20.5, 15.2, 17.4, 13.6,  8.7, 18.2, 35.4,
       31.7, 33. , 22.2, 20.4, 23.9, 25. , 12.7, 29.1, 12. , 17.7, 27. ,
       20.6, 10.2, 17.5, 19.7, 29.8, 20.5, 14.9, 10.9, 19.5, 22.7, 19.5,
       24.6, 25. , 24.5, 50. , 14.3, 11.8, 31. , 28.7, 16.2, 43.5, 25. ,
       22. , 19.9, 22.1, 46. , 22.9, 20.2, 43.1, 34.6, 13.8, 24.3, 21.5,
       24.4, 21.2, 23.8, 26.6, 25.1,  9.6, 19.4, 19.4,  9.5, 14. , 26.5,
       13.8, 34.7, 16.3, 21.7, 17.5, 15.6, 20.9, 21.7, 12.7, 18.5, 23.7,
       19.3, 12.7, 21.6, 23.2, 29.6, 21.2, 23.8, 17.1, 22. , 36.5, 18.8,
       21.9, 23.1, 20.2, 17.4, 37. , 24.1, 36.2, 15.7, 32.2, 13.5, 17.9,
       13.3, 11.7, 41.7, 18.4, 13.1, 25. , 21.2, 16. , 34.9, 25.2, 24.8,
       21.5, 23.4, 18.9, 10.8, 21. , 27.5, 17.5, 13.5, 28.7, 14.8, 19.1,
       28.6, 13.1, 19. , 11.3, 13.3, 22.4, 20.1, 18.2, 22.9, 20.6, 25. ,
       12.8, 34.9, 23.7, 50. , 29. , 30.1, 22. , 15.6, 23.3, 30.1, 14.3,
       22.8, 50. , 20.8,  6.3, 34.9, 32.4, 19.9, 20

In [13]:
X_test

array([[6.72400e-02, 0.00000e+00, 3.24000e+00, ..., 1.69000e+01,
        3.75210e+02, 7.34000e+00],
       [9.23230e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.66150e+02, 9.53000e+00],
       [1.14250e-01, 0.00000e+00, 1.38900e+01, ..., 1.64000e+01,
        3.93740e+02, 1.05000e+01],
       ...,
       [1.68118e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 3.08100e+01],
       [4.92980e-01, 0.00000e+00, 9.90000e+00, ..., 1.84000e+01,
        3.96900e+02, 4.54000e+00],
       [2.98500e-02, 0.00000e+00, 2.18000e+00, ..., 1.87000e+01,
        3.94120e+02, 5.21000e+00]])

In [14]:
model = Sequential()
model.add(Dense(30,input_dim=13,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(1))

In [15]:
model.compile(loss='mse',
              optimizer='adam')

In [16]:
model.fit(X_train,Y_train,epochs=200,batch_size=10,verbose=0)

In [17]:
Y_prediction=model.predict(X_test).flatten()

In [18]:
Y_prediction=Y_prediction.astype(float)

In [19]:
Y_prediction

array([6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.28234959, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.32134342, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177065,
       6.34177065, 6.34177065, 6.34177065, 6.34177065, 6.34177

In [20]:
for i in range(10):
  label=Y_test[i]
  prediction = Y_prediction[i]
  print("실제가격: {:.3f}, 예상가격: {:.3f}".format(label, prediction))

실제가격: 22.600, 예상가격: 6.342
실제가격: 50.000, 예상가격: 6.342
실제가격: 23.000, 예상가격: 6.342
실제가격: 8.300, 예상가격: 6.342
실제가격: 21.200, 예상가격: 6.342
실제가격: 19.900, 예상가격: 6.342
실제가격: 20.600, 예상가격: 6.342
실제가격: 18.700, 예상가격: 6.342
실제가격: 16.100, 예상가격: 6.342
실제가격: 18.600, 예상가격: 6.342


In [21]:
model.predict(X_test)

array([[6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.2823496],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
       [6.3417706],
